### ISSUE TITLE
redis-sentinel didn't completed the election

### ISSUE THREAD

**Issue by wchao1241** [kubernetes/examples#103]
After execute “kubectl delete pods redis-master”
kubectl logs -f redis-sentinel：
12:X 26 Sep 01:10:02.266 # +monitor master mymaster 172.17.109.163 6379 quorum 2
12:X 26 Sep 01:10:02.267 * +slave slave 192.168.250.49:6379 192.168.250.49 6379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:10:03.401 * +sentinel sentinel 489c70f345a51146d384a39830b0b7c069605f59 172.17.109.145 26379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:10:03.742 * +sentinel sentinel aa7ee4d01c938fca50204f49e3f9a2a8dd73b537 172.17.109.163 26379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:10:05.243 * +sentinel sentinel 5f5328394e1ba2ddbe002d2b3d35cc244a4b16f6 172.17.109.110 26379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:11:02.337 # +sdown slave 192.168.250.49:6379 192.168.250.49 6379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:12:44.216 # +sdown master mymaster 172.17.109.163 6379
12:X 26 Sep 01:12:44.217 # +sdown sentinel aa7ee4d01c938fca50204f49e3f9a2a8dd73b537 172.17.109.163 26379 @ mymaster 172.17.109.163 6379
12:X 26 Sep 01:12:44.367 # +new-epoch 1
12:X 26 Sep 01:12:44.420 # +vote-for-leader 489c70f345a51146d384a39830b0b7c069605f59 1
12:X 26 Sep 01:12:45.296 # +odown master mymaster 172.17.109.163 6379 #quorum 3/2
12:X 26 Sep 01:12:45.296 # Next failover delay: I will not start a failover before Tue Sep 26 01:18:44 2017
12:X 26 Sep 01:18:44.691 # +new-epoch 2
12:X 26 Sep 01:18:44.691 # +try-failover master mymaster 172.17.109.163 6379
12:X 26 Sep 01:18:44.733 # +vote-for-leader 67c6de61fc6be502e9fd0b2ae1be056ddc192aea 2
12:X 26 Sep 01:18:44.822 # 489c70f345a51146d384a39830b0b7c069605f59 voted for 67c6de61fc6be502e9fd0b2ae1be056ddc192aea 2
12:X 26 Sep 01:18:44.840 # 5f5328394e1ba2ddbe002d2b3d35cc244a4b16f6 voted for 67c6de61fc6be502e9fd0b2ae1be056ddc192aea 2
12:X 26 Sep 01:18:44.850 # +elected-leader master mymaster 172.17.109.163 6379
12:X 26 Sep 01:18:44.850 # +failover-state-select-slave master mymaster 172.17.109.163 6379
12:X 26 Sep 01:18:44.914 # -failover-abort-no-good-slave master mymaster 172.17.109.163 6379
12:X 26 Sep 01:18:44.985 # Next failover delay: I will not start a failover before Tue Sep 26 01:24:45 2017
12:X 26 Sep 01:24:45.127 # +new-epoch 3
12:X 26 Sep 01:24:45.187 # +vote-for-leader 489c70f345a51146d384a39830b0b7c069605f59 3
12:X 26 Sep 01:24:45.187 # Next failover delay: I will not start a failover before Tue Sep 26 01:30:45 2017

kubectl logs -f redis-td4wq：
14:S 26 Sep 01:24:57.030 * MASTER <-> SLAVE sync started
14:S 26 Sep 01:25:58.153 # Timeout connecting to the MASTER...
14:S 26 Sep 01:25:58.153 * Connecting to MASTER 172.17.109.163:6379
14:S 26 Sep 01:25:58.153 * MASTER <-> SLAVE sync started

redis-sentinel didn't  completed the election

**Comment by wchao1241** [comment]
# Replication
role:master
connected_slaves:2
slave0:ip=192.168.250.49,port=6379,state=online,offset=6695,lag=0
slave1:ip=192.168.250.49,port=6379,state=online,offset=6695,lag=0
master_repl_offset:6695
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2
repl_backlog_histlen:6694
-------------------------------------------------------------------
sentinel myid 93cf62df8d71167238bb0f5965013893090c6338
sentinel monitor mymaster 172.17.109.189 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel config-epoch mymaster 0
bind 0.0.0.0
# Generated by CONFIG REWRITE
port 26379
dir "/"
protected-mode no
sentinel leader-epoch mymaster 0
sentinel known-slave mymaster 192.168.250.49 6379
sentinel known-sentinel mymaster 172.17.109.189 26379 8ec40dc85934ea1c2a004e15ff1687f286b4105d
sentinel current-epoch 0
---------------------------------------------------------
I think the problem lies in:
the IP of slave0 and slave1 is same(host IP),   Only one IP can be obtained in redis-sentinel，so redis-sentinel didn't completed the election

**Comment by ZhenyangZhao** [comment]
@Miyurz I have the same problems.
Could you please take a few minutes to look at it?
Thanks a lot.
