### ISSUE TITLE
HTTP 403 User "system:serviceaccount:default:elasticsearch" cannot get endpoints in the namespace "default".

### ISSUE THREAD

**Issue by nottinhill** [kubernetes/examples#105]
Regarding: https://github.com/kubernetes/examples/tree/master/staging/elasticsearch

I get:

`Exception caught during discovery javax.ws.rs.WebApplicationException : HTTP 403 User "system:serviceaccount:default:elasticsearch" cannot get endpoints in the namespace "default".`

Full:
```
tyrion@Stephans-MBP ~/d/s/s/elastic> kubectl logs -f elastic-f7qxr
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
[2017-10-02 13:26:23,995][INFO ][node                     ] [D'Ken] version[1.7.1], pid[7], build[b88f43f/2015-07-29T09:54:16Z]
[2017-10-02 13:26:23,995][INFO ][node                     ] [D'Ken] initializing ...
[2017-10-02 13:26:24,219][INFO ][plugins                  ] [D'Ken] loaded [cloud-kubernetes], sites []
[2017-10-02 13:26:24,280][INFO ][env                      ] [D'Ken] using [1] data paths, mounts [[/data (/dev/xvda9)]], net usable_space [11.6gb], net total_space [28.6gb], types [ext4]
[2017-10-02 13:26:27,985][INFO ][node                     ] [D'Ken] initialized
[2017-10-02 13:26:27,985][INFO ][node                     ] [D'Ken] starting ...
[2017-10-02 13:26:28,186][INFO ][transport                ] [D'Ken] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.2.6.148:9300]}
[2017-10-02 13:26:28,215][INFO ][discovery                ] [D'Ken] myesdb/EUCn0wAqQjSOUVpqrC4lZQ
[2017-10-02 13:26:30,737][WARN ][io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider] [D'Ken] Exception caught during discovery javax.ws.rs.WebApplicationException : HTTP 403 User "system:serviceaccount:default:elasticsearch" cannot get endpoints in the namespace "default".
```

I have no idea how to fix this. I did everything as on the GitHub Readme.

**Comment by antoineco** [comment]
Do you have RBAC enabled in your cluster? If so, you have to create a ClusterRoleBinding (and optionally a ClusterRole) for the `elasticsearch` service account.

Try this:
`kubectl create rolebinding elasticsearch --clusterrole=view --serviceaccount=elasticsearch --namespace=default`

**Comment by nottinhill** [comment]
Hi thanks for this.

When I try it I get:

> error: serviceaccount must be <namespace>:<name>

So I started reading Docs and it says only of 1.8 this is stable. But seems to me 1.7.3-tectonic-1 is the latest I can install.

Any ideas?

> Am 04.10.2017 um 07:47 schrieb Antoine Cotten <notifications@github.com>:
> 
> kubectl create rolebinding elasticsearch --clusterrole=view --serviceaccount=elasticsearch --namespace=default

**Comment by nottinhill** [comment]
Hi thanks a lot for this.

When I try it I get:

> error: serviceaccount must be <namespace>:<name>

So I started reading Docs and it says only of 1.8 this is stable. But seems to me 1.7.3-tectonic-1 is the latest I can install.

I then went to my tectonic console and did it via GUI. Please confirm correctness:

![screenshot](https://user-images.githubusercontent.com/418352/31173266-22bfa9f8-a907-11e7-9d8e-213c94f27595.png)

```
kubectl get serviceaccounts
NAME            SECRETS   AGE
default         1         22d
elasticsearch   1         3d
```

and:

```
kubectl get serviceaccounts/elasticsearch -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2017-10-01T10:49:26Z
  name: elasticsearch
  namespace: default
  resourceVersion: "5398045"
  selfLink: /api/v1/namespaces/default/serviceaccounts/elasticsearch
  uid: 31c9a776-a696-11e7-ad6e-06c35bf26544
secrets:
- name: elasticsearch-token-hh6r9
```

**Comment by antoineco** [comment]
Let's stick to the authentication issue :) Ingress access is a whole different concern.

`RoleBinding` applies only to the namespace it's deployed in. In the case, the `default` namespace. Are you deploying ES to that namespace?

**Comment by nottinhill** [comment]
I used all 3 example yaml files unaltered. 
Now after reading your comment I added `namespace=default` to all metadata.

**Comment by antoineco** [comment]
The manifests don't necessarily define the namespace, but the configuration of your client do.

That said, I think it would be worth adding a valid `RoleBinding` to the example.

**Comment by nottinhill** [comment]
Sure, a *working* RoleBinding will always be add-worthy. However, at the moment, it is not working. I have a default tectonic install, recently set up. Nothing out of the ordinary. If we can't get the binding to run on my cluster, it won't run on custom clusters either.

**Comment by antoineco** [comment]
I'll push a working RBAC setup in a second (Role, RoleBinding).

**Comment by nottinhill** [comment]
Had a chance to push a setup yet?

**Comment by antoineco** [comment]
I'm setting up a cluster to test right now, since the elasticsearch plugin doesn't document the permissions it needs.
