### ISSUE TITLE
Cassandra: statefulset and volume constraint prevents Cassandra pods from healing

### ISSUE THREAD

**Issue by VinceMD** [kubernetes/examples#149]
Running Cassandra in AWS but I imagine the same applies elsewhere (Kubernetes 1.7.4). Consider:

3 Cassandra nodes as defined by the Statefulset.

- cassandra-0 is in AZ "a"
- cassandra-1 is in AZ "b"
- cassandra-2 is in AZ "c"

AZ stands for a Availability Zone (same as Google Zone I heard). It's like a rack (although we don't have Kubernetes Cassandra snitch so for Cassandra it looks like everything is in one rack)

I shutdown all Kubernetes nodes in AZ "a" and prevent creating new nodes in AZ "a"
Therefore cassandra-0 cannot start as its EBS Volume (PV) is tight to the AZ "a".

This simulates 1 Availability Zone (zone) down. 

During this time cassandra-2 fails and needs to be restarted elsewhere. 
A statefulset won't self-heal cassandra-2 and also prevents creating further cassandra-3,  cassandra-4, etc.
If we also loose cassandra-1 (maybe the host is gone because of AWS/Cloud autoscaling), then we have no Cassandra node left. The more time the first zone is down, the more we risk having to re-create the other Cassandra nodes (infra is elastic and hosts can go wrong), which is not working unless AZ "a" goes back online. For a 30minutes outage of AZ "a", it will be fine. But then the clock is ticking...

From Statefulset doc:
"Before a scaling operation is applied to a Pod, all of its predecessors must be Running and Ready."

Some questions

- Is that expected behaviour?
- shouldn't we allow Cassandra to scale nodes in other AZ even if the first one is down?
- Is Statefulset the right choice then? would deployment + replica work better? (as far as I know we need the seeds to start first, thereafter we don't care about the order).
- Should we use 3 statefulset (1 per zone/rack) joining the same cluster? How to do that? How do Cassandra node recognise they are in the same cluster? Is there any issue with this approach?

**Comment by ahmetb** [comment]
I recommend asking this on kubernetes-users Google Groups forum.

**Comment by VinceMD** [comment]
@ahmetb after some research and indeed asking questions to others, there are 2 solutions:

- in recent versions of K8S we can tell a statefulset to do things in parallel when it comes to provisioning nodes. This is tricky with Cassandra as at least the seed nodes need to be up first. Could use another mechanism for the seeds and rely on statefulset for normal nodes.

- my solution was to create 3 statefulsets. 1 per AZ. Each statefulset defines a seed node, so 1 seed per AZ. The trick is to ensure the first seed has started before starting the 2 other statefulsets (no need to wait for the entire first statefulset to be complete, just wait for the seed nodes).
This will prevent split brain cluster on first boot.
The logic to wait for the seed node of the first statefulset to be up and running can be orchestrated with a CI/CD tool such as Jenkins. There might be a cleaner way to do this with K8S

Your list of seed nodes need to contain all 3 seeds:
cassandraA-0.cassandra.%%NAMESPACE%%.svc.cluster.local, cassandraB-0.cassandra.%%NAMESPACE%%.svc.cluster.local, cassandraC-0.cassandra.%%NAMESPACE%%.svc.cluster.local, 

Where cassandraA, cassandraB, cassandraC are the names of the different statefulset.
You have to use 3 different storage class, one for each AZ to prevent the EBS to be provisioned in the wrong AZ (K8S is not smart enough yet to do it dynamically)
Each statefulset will also have node affinity to start in the right AZ. So both ensure statefulset are contained in its own AZ.

Sounds complicated but it's not difficult to implement. It's kind of helpful to being able and treat the 3 AZ separately.  With a replication factor = 3, I ensure I have a copy of the data in each AZ. I can simulate an AZ failure by simply turning off a statefulset (replica=0)

**Comment by ahmetb** [comment]
I'm not at all familiar with the Cassandra example, I'll cc @aledbf who has been maintaining that example recently.
