### ISSUE TITLE
Removing example labels out of core

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/examples#15]
Since C* example is over here can we remove https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+Cassandra+label%3Aarea%2Fexample%2Fcassandra labels?

**Comment by ahmetb** [comment]
@kubernetes/sig-contributor-experience-misc, can we remove the `area/example/cassandra ` label from the kubernetes/kubernetes? This repository is the new location for examples.

**Comment by sebgoa** [comment]
@chrislovecnm what happens if we remove that label ? you won't be able to search back based on that label in the original repo (because the label will be gone).
