### ISSUE TITLE
issue with spark-ui-proxy

### ISSUE THREAD

**Issue by Arnold1** [kubernetes/examples#152]
Hi,

I followed all steps until Step 2:
```
$ kubectl create -f staging/spark/spark-ui-proxy-controller.yaml
replicationcontroller "spark-ui-proxy-controller" created

$ kubectl create -f staging/spark/spark-ui-proxy-service.yaml
service "spark-ui-proxy" created

$ kubectl get svc spark-ui-proxy -o wide
NAME             TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE       SELECTOR
spark-ui-proxy   LoadBalancer   10.0.0.38    <pending>     80:31945/TCP   9m        component=spark-ui-proxy
```

i dont get the external IP, why is that? i waited 10 min between spark-ui-proxy and kubectl get svc spark-ui-proxy -o wide...

**Comment by huxiaoliang** [comment]
@Arnold1  this is not an issue, since LoadBalancer type service need a cloud provider such as  GCE,  do you have it?

**Comment by anantpukale** [comment]
@huxiaoliang I am also having same issue and I am running it on GCE . 
Note : It was working earlier and external ip was showing up .

**Comment by Arnold1** [comment]
hi, what is GCE and how to install it? does it say that in step 2?
