### ISSUE TITLE
How to setup a hadoop cluster in a kubernetes cluster?

### ISSUE THREAD

**Issue by dahaian** [kubernetes/examples#155]
I would like to setup a hadoop cluster in a kubernetes cluster.There are 4 nodes for kubernetes cluster.
I create a pod for hadoop master in a kubernetes cluster node.And I create three pods for hadoop slaves in the other 3 nodes.I have to do that all the pods in a intranet each other.I want to do that multiple pods in different nodes in a intranet. What should I do?Any help is appreciated!

**Comment by ahmetb** [comment]
Please ask ok Slack or Kubernetes-users@ Google Groups mailing list. 😊
