### ISSUE TITLE
How can I customize elasticsearch.yaml

### ISSUE THREAD

**Issue by bainim** [kubernetes/examples#157]
Hello every one ,
i'm working on kubernetes and elasticsearch
i followed this link :https://github.com/kubernetes/examples/tree/master/staging/elasticsearch
what i want is to add a volume to be like this on :
folder_path/config/elasticsearch.yml:/root/config/elasticsearch.yml

**Comment by ahmetb** [comment]
Please ask questions on kubernetes Slack (http://slack.k8s.io/) or the mailing list (https://groups.google.com/forum/#!forum/kubernetes-users).

**Comment by bainim** [comment]
Thank you for the help
