### ISSUE TITLE
Using the Azure Disk example with AKS results in PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by toddysm** [kubernetes/examples#158]
We are trying the Azure Disk example on Azure Managed Kubernetes and it fails with `PersistentVolumeClaim is not bound`
Also, it is not clear from the example documentation what storage account and what credentials are used by the Kubernetes cluster to create the disk.

**Comment by ahmetb** [comment]
Please ask questions on kubernetes-users email list or Slack (slack.k8s.io).

**Comment by toddysm** [comment]
@ahmetb I will gladly ask questions there but the point of this issue is to improve the examples.

**Comment by ahmetb** [comment]
Sorry my bad. I misread.

**Comment by StianOvrevage** [comment]
@toddysm Does that mean you have successfully gotten the PersistentVolumeClaims to work? Care to share how?

**Comment by akunaatrium** [comment]
I have the same problem.

**Comment by gmoed** [comment]
I get the same warnings, seems to be a delay on the disk creation process, after a while I get confirmation about disk being mounted
