### ISSUE TITLE
Change in redis-master.yaml

### ISSUE THREAD

**Issue by jbauza1984** [kubernetes/examples#169]
line 12 -> image: gcr.io/google-containers/redis:latest

**Comment by ahmetb** [comment]
Can you elaborate further why this change is needed?

**Comment by jbauza1984** [comment]
Yes, use k8s.gcr.io/redis:v1 returns error: "Failed to pull image "k8s.gcr.io/redis:v1": failed to run [fetch --no-store docker://k8s.gcr.io/redis:v1]: exit status 254"

**Comment by ahmetb** [comment]
We recently migrated from `gcr.io/google-containers` to k8s.gcr.io`. If there's any issues with it, please file them at https://github.com/kubernetes/k8s.io/.

Personally, `k8s.gcr.io/redis:v1` works for me.
