### ISSUE TITLE
KubernetesSeedProvider: endpoints null for first node

### ISSUE THREAD

**Issue by gkumar7** [kubernetes/examples#190]
https://github.com/kubernetes/examples/blob/8774c894fa623dcc7a43bdfdc4fbf5668074fadf/cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java#L134-L137

Regarding this comment, are there any other scenarios in which ```endpoints``` can be null? If not, possibly the local ip could be placed in the seed list instead of using the default seeds list.

**Comment by gkumar7** [comment]
@chrislovecnm maybe you can provide some insight?

**Comment by chrislovecnm** [comment]
Have not used this code in a long time ;(

**Comment by gkumar7** [comment]
Is there a newer version of the seed provider I could reference?
