### ISSUE TITLE
Incompatible certificate name

### ISSUE THREAD

**Issue by mau21mau** [kubernetes/examples#194]
Your `nginx.conf` file points the certs to `nginx.cert` and `nginx.key`, while your inside the mount point they are called `tls.cert` and `tls.key`.

**Comment by ahmetb** [comment]
@mau21mau I'm not sure which particular example you're talking about, there are tens of examples in this repo, and multiple of them containing nginx. If you have fixes, please contribute them as pull requests.

**Comment by levmichael3** [comment]
I think he is talking about this issue while on the secret we get tls.key and tls.crt 
```
kubectl describe secret 
Name:         default-token-7gmck
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name=default
              kubernetes.io/service-account.uid=****

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1115 bytes
namespace:  7 bytes
token:      ****


Name:         nginxsecret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  1143 bytes    ##### <<<<<<<<<<<<
tls.key:  1704 bytes    ##### <<<<<<<<<<<<
```


while on default.conf
```
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        listen 443 ssl;

        root /usr/share/nginx/html;
        index index.html;

        server_name localhost;
        ssl_certificate /etc/nginx/ssl/nginx.crt;   ##### <<<<<<<<<<<<
        ssl_certificate_key /etc/nginx/ssl/nginx.key;  ##### <<<<<<<<<<<<

        location / {
                try_files $uri $uri/ =404;
        }
}
```

**Comment by ahmetb** [comment]
Still not sure what example this is about. Can you link to the particular example directory, there's tens of them in this repo.

**Comment by mau21mau** [comment]
It's related to [parse chart](https://github.com/kubernetes/charts/tree/master/stable/parse).

**Comment by ahmetb** [comment]
Apologies but this is not the "charts" repo. There's no Parse-related content in this "examples" repo. If you have an issue with the chart, please open an issue in the charts repo.

**Comment by mau21mau** [comment]
I'm sorry. Commented on the wrong window. Actually this is on the nginx ssl configuration:
https://github.com/kubernetes/examples/blob/master/staging/https-nginx/README.md

**Comment by ahmetb** [comment]
Got it! This simply looks like an error. Feel free to send a pull request to fix it.

**Comment by ahmetb** [comment]
@mau21mau any interest in sending a pull request?

**Comment by levmichael3** [comment]
@ahmetb @mau21mau I would love to send one.
It will be either renaming the `ssl_certificate` parameters in the default.conf file + README or creating different names for the files in the `nginxsecret` secret. I didn't saw documentation on how to do it, can anyone show me please?  

```
# kubectl describe secret nginxsecret 
Name:         nginxsecret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  1143 bytes   #<<< change this to nginx.crt
tls.key:  1708 bytes  #<<< change this to nginx.key
```

**Comment by ahmetb** [comment]
I can fix this. I think you're not supposed to change tls.crt/tls.key as those are standard (from `kubectl create secret tls` command).

**Comment by ahmetb** [comment]
Sent pull request #217.
