### ISSUE TITLE
Migrate tests from main repo

### ISSUE THREAD

**Issue by serathius** [kubernetes/examples#214]
I'm working on PR that removes `examples` directory from main repo.
I found more advanced tests in https://github.com/kubernetes/kubernetes/blob/67be0a90f44a82985e6f926c102d2427a887a893/test/e2e/examples.go
Maybe they could be used as a base for testing examples.

**Comment by ahmetb** [comment]
I believe those were mostly used to validate the YAML file formats (so that the tutorials aren't broken). The code doesn't apply to the majority of the repo. I'll leave it up to you, but I think the gains are minimal on this one.
