### ISSUE TITLE
nfs mount failed on other nodes

### ISSUE THREAD

**Issue by do-web** [kubernetes/examples#220]
I tried https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs

I have running two nodes if i start the nginx server the pod on the server where the nfs-server is running, can connect to the nfs. But on the other node the pod throws an error:

`
MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: -description=Kubernetes transient mount for /var/lib/kubelet/pods/4df483ce-2eb4-11e8-b73c-02f3569a6c30/volumes/kubernetes.io~nfs/nfs --scope - mount -t nfs 10.43.103.112:/ /var/lib/kubelet/pods/4df483ce-2eb4-11e8-b73c-02f3569a6c30/volumes/kubernetes.io~nfs/nfs Output: Running scope as unit run-r7f98d0cc28f24eea92d7ab1eaaac6312.scope. 
mount.nfs: access denied by server while mounting 10.43.103.112:/
`

What is here wrong?

**Comment by TonyCMCC** [comment]
there is wrong with access right,u can config access rule on the nfs server
