### ISSUE TITLE
staging/volumes/cephfs mention base64

### ISSUE THREAD

**Issue by rvernica** [kubernetes/examples#238]
For setting up the Sectret for Ceph, it might be worth mentioning that `ceph-authtool -p /etc/ceph/ceph.client.admin.keyring` returns a Base64 string, but one needs to re-encode that with Base64. So, in the Kubernetes Secret you put the output of:
```
ceph-authtool -p /etc/ceph/ceph.client.admin.keyring | base64
```
Otherwise, one will get a strange `fork/exec nsenter: invalid argument` error.

**Comment by rocdove** [comment]
> ceph-authtool -p /etc/ceph/ceph.client.admin.keyring | base64

use base64 error still.
event:  mount error 22 = Invalid argument failed to load ceph kernel module 

stringData:
  key: xxxx  # ceph-authtool -p /etc/ceph/ceph.client.admin.keyring
