### ISSUE TITLE
MySQL Wordpress PV example giving errors.

### ISSUE THREAD

**Issue by mbtamuli** [kubernetes/examples#24]
**What happened**:
I was following the Stateful Applications example - [Wordpress MySQL persistent volume](https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/)
In the [Deploy MySQL](https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#deploy-mysql) step, I encountered an error. I did `describe` on the pod. It was showing this error. 
```
SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "mysql-pv-claim", which is unexpected.
```
The full output of `kubectl describe pod` is [here](http://sprunge.us/jeHQ). I also checked whether the PersistentVolume was created and whether a PersistentVolumeClaim was created - [here](http://sprunge.us/JWfP)

**What you expected to happen**:
I expected the MySQL pod to be up as the tutorial suggested. At least the tutorial should mention any such issues if they are known and link to an explanation, if possible.

**How to reproduce it (as minimally and precisely as possible)**:
```
gcloud container clusters create wp --num-nodes=3
gcloud compute disks create --size=20GB wordpress-1 wordpress-2
export KUBE_REPO=https://raw.githubusercontent.com/kubernetes/examples/master
kubectl create -f $KUBE_REPO/mysql-wordpress-pd/gce-volumes.yaml
tr --delete '\n' <password.txt >.strippedpassword.txt && mv .strippedpassword.txt password.txt
kubectl create secret generic mysql-pass --from-file=password.txt
kubectl create -f $KUBE_REPO/mysql-wordpress-pd/mysql-deployment.yaml
```
Now running `kubectl get pods` will show status as _CrashLoopBackOff_ or _Error_ in a few minutes.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 
```
BUILD_ID=9202.64.0
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=57
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=57
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`): 
```
Linux gke-wp-default-pool-a7a7b2f3-0cbs 4.4.35+ #1 SMP Wed Apr 5 13:00:57 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by mbtamuli** [comment]
It was reported here too in this [issue](https://github.com/kubernetes/kubernetes/issues/41046). Sorry for this duplicate issue, but that issue was closed without explaining the reason for this error.
I tried the fix mentioned in the issue, adding annotation to the PVC - 
```
annotations:
volume.beta.kubernetes.io/storage-class: ""
```

It works. Why is it required though?

**Comment by minac** [comment]
Same problem here. It definitely is a problem with the claims part. :(

**Comment by hbokh** [comment]
/reopen

Getting a `CreateContainerConfigError`and `"Error: couldn't find key password in Secret default/mysql-pass"`

My workaround: instead of `password.txt`, use`password`.
Other: use `key: password.txt` in the manifest file `mysql-deployment.yaml`.
