### ISSUE TITLE
Google image V14 ,Kubernetes /KOPS Cluster on AWS is very slow 

### ISSUE THREAD

**Issue by madireddyr** [kubernetes/examples#250]
we were able to use above example KOPS cluster and able to bring up the cluster( 6 ec2 nodes), we tried with both EBS & EC2 Instance storage but writing data to root  and  they both work . but when we we do a stress test on this performance seems  very low. 
using both instance storage & EBS storage,

few stats : queue length is very low "0.06"

and OPS Stats
Results:
Op rate                   :      966 op/s  [WRITE: 966 op/s]
Partition rate            :      966 pk/s  [WRITE: 966 pk/s]
Row rate                  :      966 row/s [WRITE: 966 row/s]
Latency mean              :   51.2 ms [WRITE: 51.2 ms]
Latency median            :    7.8 ms [WRITE: 7.8 ms]
Latency 95th percentile   :  103.2 ms [WRITE: 103.2 ms]
Latency 99th percentile   :  198.3 ms [WRITE: 198.3 ms]
Latency 99.9th percentile :  298.3 ms [WRITE: 298.3 ms]
Latency max               :  601.4 ms [WRITE: 601.4 ms]
Total partitions          :    100,000 [WRITE: 100,000]
Total errors              :          0 [WRITE: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:01:43

we tried to compare the performance kubernetes 1.4.8 & Cassandra 3.9 which is our current working cluster which give 20,000 OP/sec

our KOPS statefulset cluster capacity is same as Above Kuberentes 1.4.8 with  same cassandra.yaml settings 

but cassandra performance on kubernetes 1.4.8 Perf seems much better than 1.9 KOPS
anybody faced similar issue ?
also is there a way to benchmark network performance of KOPS cluster vs kubernetes 1.4.8

**Comment by pontiyaraja** [comment]
CI job also taking long time to build and returning time out, for 1 or two times
