### ISSUE TITLE
How to write data?

### ISSUE THREAD

**Issue by gouki777** [kubernetes/examples#282]
hi 
i look you kubernetes-redis-controller. but I have a question.
how do read redis-data?   how do write redis-master data? 

I write same data in kubernetes-redis-master.
set key1 111;

[root ~]# kubectl get po,svc
NAME                             READY     STATUS    RESTARTS   AGE
pod/redis-6zgld                  1/1       Running   0          16m
pod/redis-ldbzl                  1/1       Running   0          2h
pod/redis-sentinel-4dgwc         1/1       Running   0          2h
pod/redis-sentinel-7bxsh         1/1       Running   0          2h
pod/redis-sentinel-nzbjs         1/1       Running   0          2h
pod/redis-wj8kj                  1/1       Running   0          13m
NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/kubernetes       ClusterIP   10.96.0.1      <none>        443/TCP     138d
service/redis-sentinel   ClusterIP   10.98.6.156    <none>        26379/TCP   2h

[root ~]# telnet 10.98.6.156 26379
Trying 10.98.6.156...
Connected to 10.98.6.156.
Escape character is '^]'.
ping
+PONG
SET eee 444
-ERR unknown command 'SET'
SELECT index
-ERR unknown command 'SELECT'
keys *
-ERR unknown command 'keys'

**Comment by morrofino** [comment]
Hi, did you find how to write data to redis?

Thanks
