### ISSUE TITLE
Redis SVC Question

### ISSUE THREAD

**Issue by meirhazonAnyVision** [kubernetes/examples#293]
Hello,
Can you please explain how should application connect to the redis?
There is no service for connecting to port 6379 on the redis nodes?
Can you please explain?
Thanks so much,
Meir

**Comment by JeeveshN** [comment]
@meirhazonAnyVision Did you figure this one out ?
@brendandburns

**Comment by rdxmb** [comment]
If you use https://github.com/kubernetes/examples/tree/master/staging/storage/redis you have to connect the redis-sentinel:

https://github.com/kubernetes/examples/blob/master/staging/storage/redis/redis-sentinel-service.yaml
