### ISSUE TITLE
Handle existing issues in kubernetes/kubernetes

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/examples#3]
Do we declared bankruptcy on existing issues in main repo ?
Or try to move things over ?

**Comment by kargakis** [comment]
See comment in https://github.com/kubernetes/kubernetes/issues/13944#issuecomment-307472375

**Comment by kargakis** [comment]
FWIW, the number of issues tagged as examples is not prohibitive for moving them over here: https://github.com/kubernetes/kubernetes/issues?page=1&q=is%3Aissue+is%3Aopen+label%3Aarea%2Fexample&utf8=%E2%9C%93

**Comment by sebgoa** [comment]
Then I would say we move them, but we need to tell the issue creator that the issue will not be worked on in a new repo.
