### ISSUE TITLE
newrelic-infrastructure: exec: \"bash\": stat bash: no such file or directory

### ISSUE THREAD

**Issue by sonots** [kubernetes/examples#308]
With https://github.com/kubernetes/examples/blob/master/staging/newrelic-infrastructure/newrelic-infra-daemonset.yaml, I got errors like:

```
Error: failed to start container "newrelic": Error response from daemon: oci runtime error: container
_linux.go:247: starting container process caused "exec: \"bash\": stat bash: no such file or directory"
```

Indeed, `bash` did not exist as:

```
$ docker run -it newrelic/infrastructure:latest ls -l /bin/bash
ls: /bin/bash: No such file or directory
```

**Comment by enzoTrevisan** [comment]
In the container the command bash seems didn't exist,  give it a try to /bin/sh like below
command: [ "/bin/sh", "-c", "source /etc/kube-nr-infra/config && /usr/bin/newrelic-infra" ]
