### ISSUE TITLE
I use vsphere storage, but it doesn't work

### ISSUE THREAD

**Issue by xuzhiguang** [kubernetes/examples#325]
error: AttachVolume.Attach failed for volume "test-volume" : No VM found
MountVolume.SetUp failed for volume "test-volume" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/99ccd359-8c47-11e9-a6fb-0050569905cd/volumes/kubernetes.io~vsphere-volume/test-volume --scope -- mount -o bind /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[HP6500] volumes/myDisk.vmdk /var/lib/kubelet/pods/99ccd359-8c47-11e9-a6fb-0050569905cd/volumes/kubernetes.io~vsphere-volume/test-volume Output: Running scope as unit run-15838.scope. mount: special device /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[HP6500] volumes/myDisk.vmdk does not exist

govc can work. I don't know what went wrong. what should I do?

**Comment by tirelibirefe** [comment]
Hello @xuzhiguang 
Probably you followed official vmware tutorial which is https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/kubernetes-volumes.html
I face with the same problem. How did you fix that problem?
