### ISSUE TITLE
Statefulset example pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by Nurlan199206** [kubernetes/examples#329]
I'm trying to deploy `StatefulSet` on kubernetes 1.14.3 on Ubuntu 18.10. I have "`pod has unbound immediate PersistentVolumeClaims`" message. May be i missing something?

[https://github.com/kubernetes/examples/blob/master/staging/volumes/vsphere/simple-statefulset.yaml](https://github.com/kubernetes/examples/blob/master/staging/volumes/vsphere/simple-statefulset.yaml)

**Comment by enzoTrevisan** [comment]
What kind of volume and storageclass was binded to your pod ?
