### ISSUE TITLE
Why does the /staging directory exist?

### ISSUE THREAD

**Issue by liggitt** [kubernetes/examples#334]
> It moves all current examples into a /staging directory to prepare for a cleanup .

is the cleanup still planned? https://github.com/kubernetes/kubernetes/pull/80356/files is attempting to update links to things in this subfolder folder, but I'm not sure why it exists

_Originally posted by @liggitt in https://github.com/kubernetes/examples/pull/2#issuecomment-515138884_

**Comment by ahmetb** [comment]
We migrated this repo from k/k repository's ./examples directory.

After that, we moved officially maintained examples that are referenced in the tutorials on k8s.io to the root of this directory, and moved everything else to `staging/` with the hopes of deleting them someday.

Maybe we're already past that "some day", it's hard to tell. The community might find be still finding examples in `staging/` somewhat useful –but we have no data on that. So we wanted to err on the safe side and keep them.

That said I'm not maintaining this repo anymore, so I defer the decision to current owners.
