### ISSUE TITLE
YAML files no longer exist

### ISSUE THREAD

**Issue by kd2eom** [kubernetes/examples#337]
[This guide](https://github.com/kubernetes/examples/tree/master/staging/storage/minio) says to run the command `kubectl create -f https://github.com/kubernetes/kubernetes/blob/master/examples/storage/minio/minio-standalone-pvc.yaml?raw=true`.

Doing so results in a 404 file not found error; the file seems to have moved. Could the tutorial please be updated?

**Comment by kd2eom** [comment]
Also, even if I copy and paste the text to a file and try to `kubectl create` that, it returns `error validating data: ValidationError(PersistentVolumeClaim.metadata): unknown field "storageClassName" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by vincepower** [comment]
https://github.com/kubernetes/examples/pull/342 has been submitted to resolve this.
