### ISSUE TITLE
Couldn't write on the NFS volume

### ISSUE THREAD

**Issue by s1405** [kubernetes/examples#339]
I followed the examples for NFS, however used Deployment instead of RC, wasn't able to write onto the NFS directory

$ touch sample.txt
touch: cannot touch 'sample.txt': Permission denied

This is from the NFS Pod:
cat /etc/exports
/exports *(rw,fsid=0,insecure,no_root_squash)
/ *(rw,fsid=0,insecure,no_root_squash)

The NFS Pod is connected to a GCE PD and /exports is the mount path, similar to the example

**Comment by sdanbury** [comment]
@s1405 did you find a solution to this?

**Comment by s1405** [comment]
not yet @sdanbury I was tryn to share the jobs directory of two jenkins Pods through NFS https://github.com/s1405/k8s-sample-tasks

**Comment by sdanbury** [comment]
I worked something out in the end. I basically used an init container to chown the location I was about to write to on the NFS from the main container in the pod. By default, you probably won't have permissions to write to the NFS unless your the root user. In my case, I wasn't running as the root user, so had to chown the directory first.

**Comment by s1405** [comment]
I still need to explore this, will update later, however closing the issue
