### ISSUE TITLE
Can you give me consult ? 

### ISSUE THREAD

**Issue by Inv0k-er** [kubernetes/examples#349]
Hello evreybody. Recently I start study kubernetes. And I try to understand PV and PVC with nfs.
And I really cant understand:
1. When I using nfs. Where need to deploy nfs server ? It is some independent or need to deploy in master node or minion node ? 
2. In my pvc - yaml
======================================================
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvc1
spec:
 accessModes:
   - ReadWriteMany
 capacity:
   storage: 10Gi
 nfs:
   server: - I think need to past nfs server ???? 
   path:  --- which path need to past ??? 
===============================================

**Comment by venkateshreddypala** [comment]
Each PV contains a spec and status, which is the specification and status of the volume.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
=======================================================
path is where you want the nfs to be on. It can be on host, GCP or AWS. 
I’m not 100% about the server, hope this helps.
