### ISSUE TITLE
Minio quickstart example is not working

### ISSUE THREAD

**Issue by averri** [kubernetes/examples#352]
The quick start example provided here: https://github.com/kubernetes/examples/tree/master/staging/storage/minio

... is not working. It fails with:

```
ProvisioningFailed | storageclass.storage.k8s.io "standard" not found
```

**Comment by clattems** [comment]
@averri have you tried this? https://github.com/minio/minio/tree/master/docs/erasure/storage-class#set-storage-class

**Comment by viniciusbds** [comment]
@averri have you figured out what the problem was?
