### ISSUE TITLE
Can we have multiple selenium hub pods to speed up execution?

### ISSUE THREAD

**Issue by neo81-83** [kubernetes/examples#360]
If 'yes' what are the changes required besides replica=3? Quick response would be appreciated.

**Comment by NasAmin** [comment]
I vote for this. We are running SeleniumGrid on EKS. The hub gets overwhelmed and results our tests failing frequently.

It would be really good if the hub can auto scale as well. 
Zalenium seemed like a very good tool but unfortunately it isn't being maintained anymore
https://github.com/zalando/zalenium

Regards,

Nas
