### ISSUE TITLE
How to expose this to outside kubernetes cluster ?

### ISSUE THREAD

**Issue by saurastrirajat** [kubernetes/examples#381]
I tried following this 
https://github.com/kubernetes/examples/tree/master/staging/storage/redis#tl-dr

But this setup seems to be accessible within K8S cluster. How do we expose this to outside ?

I tried changing service type to NodePort. This exposed sentinel. Then I did redis-cli to sentinel using node host and nodeport. Which connect me to sentinel and from there my redis master and slave discoverable

However when I try to connect to master from sentinel it do not connect. 

Any help or lead to solve this ?

**Comment by MoShitrit** [comment]
Hey @saurastrirajat 
Can you please provide a bit more info?
Which steps / commands exactly did you try to run? Which ones didn't work? And what was the error message?
