### ISSUE TITLE
NFS example with a cluster local service name only works on GKE but not for minikube/kubeadm

### ISSUE THREAD

**Issue by ensonic** [kubernetes/examples#390]
This might be a followup for #237. The change from IP to `server: nfs-server.default.svc.cluster.local` in
https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-pv.yaml#L11
seems to be not well tested. It works on GKE through some black magic, but neither on minikube or kubeadm clusters. The main problem is that the controller is not resolving the IP address against core-dns before building the mount command line that will be run on the node's host system.
But there is more. Even after I patched the hosts resolver so that tools like dig, host, nsloopup can resolve the cluster local name, /sbin/mount.nfs still fails.
```
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/7ecbc79e-2228-4447-9667-ef5f590d473d/volumes/kubernetes.io~nfs/nfs --scope -- mount -t nfs nfs-server.default.svc.cluster.local:/exports /var/lib/kubelet/pods/7ecbc79e-2228-4447-9667-ef5f590d473d/volumes/kubernetes.io~nfs/nfs
Output: Running scope as unit: run-rf00d34506d784765bb629f16c2941921.scope
mount.nfs: Failed to resolve server nfs-server.default.svc.cluster.local: Name or service not known
```

To be clear, no one wants to use a fixed IP address, so using the service name is a great change, but it also need to actually work :)

**Comment by ensonic** [comment]
Using a csi-driver, such as https://github.com/kubernetes-csi/csi-driver-nfs will work with an in-cluster nfs server.

**Comment by saiyam1712** [comment]
Resolving through service name would be a great change. Can it be taken into consideration asap?

**Comment by vikramparth** [comment]
I'm also running into this issue with docker desktop. Any workarounds here? Thanks.
