### ISSUE TITLE
Not able to access service in browser

### ISSUE THREAD

**Issue by patelrutva** [kubernetes/examples#414]
**Steps to reproduce the issue:** 

1. kubectl run docserver --image=docker.io/{myusername}/{image}:latest --port=80
2. kubectl expose pod docserver --type=NodePort
3. minikube service docserver

![image](https://user-images.githubusercontent.com/41102770/110014536-e7547800-7cf0-11eb-86a1-667879b97498.png)

**Full output of minikube dashboard logs:**
![image](https://user-images.githubusercontent.com/41102770/110014671-12d76280-7cf1-11eb-8121-a86fa9c3d037.png)

**But In browser getting this**
![image](https://user-images.githubusercontent.com/41102770/110014733-24b90580-7cf1-11eb-9679-4185fe437dbb.png)

<details>

how can I hit the service?

Thanks in advance.

</details>

**Comment by slashpai** [comment]
From the screenshot, the port number should be 62529, but in the browser, you are using port 62320. That appears to be the issue
