### ISSUE TITLE
Failed to resolve server nfs-server.default.svc.cluster.local: Name or service not known

### ISSUE THREAD

**Issue by Azbesciak** [kubernetes/examples#418]
Hello, I tried to use example for NFS server, with the only change that I changed in [`nfs-server-rc.yml`](https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-server-rc.yaml#L31) `persistentVolumeClaim` to 
```yaml
hostPath:
     path: /path/on/my/machine
```

I applied all NFS samples in a given order (rc, service, pv, pvc) but when I try to consume it via pvc in my job I receive an error like below
````
MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32 Mounting command: mount
Mounting arguments: -t nfs nfs-server.default.svc.cluster.local:/ /var/lib/kubelet/pods/5f4d4cce-ab59-44cb-9311-ef5fef696902/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Failed to resolve server nfs-server.default.svc.cluster.local: Name or service not known
````

Do you have any idea how to solve this? I saw in https://github.com/kubernetes/minikube/issues/3417 that I am not the one facing this issue, but I suppose that if you placed this as an example, it should work. I am using Docker for Windows with the following spec
 - docker v20.10.5
  - kubernetes v1.19.7
  - WSL 2, based on ubuntu 20.04

Also, I think I can but not sure - can I consume a single pv with multiple pvc, assuming `ReadWriteMany`? Worth to mention is that I aim to have jobs in different namespaces. I assume that each namespace must have at least dedicated for it pvc (I cannot have one global)? In general, I am looking for some substitute of `hostPath` - without NFS, but `hostPath` doest not work with multi-node cluster, so...

Thanks!

**Comment by Azbesciak** [comment]
Hello, could you please take a look at this?

**Comment by adthonb** [comment]
@Azbesciak I have the same issue. You can't use the DNS of Service. Use Cluster-IP of Service instead. Change `server:` value in `nfs-pv.yaml`

**Comment by Azbesciak** [comment]
Yup, take a look at https://github.com/kubernetes/minikube/issues/3417#issuecomment-670005434
But I rather expected some solution from k8s team.

**Comment by ronald** [comment]
We also had no success with the fqdn, although it's in the example since 2019:
https://github.com/kubernetes/examples/commit/b8ba2838ba9b1769000de7e4cd58ab0dc9a3f951#diff-c275d4aa3949dc746e724423e8efd11390c757902b9ed54b0dc6ba4eb7ace3f1

**Comment by HusseinKabbout** [comment]
I think it would be good to revert this [commit](https://github.com/kubernetes/examples/pull/295/files), as it misleads the reader to believe that using the FQDN of the NFS service should work (even though it doesn't).

From my understand, currently there are only two somewhat reasonable solutions for this problem:

1. Use the services IP instead of the FQDN
2. Manually update the nodes hosts file (`/etc/hosts`) to make using the FQDN work

/reopen
