### ISSUE TITLE
unable to open minio console with standalone mino pod

### ISSUE THREAD

**Issue by devivaraprasad901** [kubernetes/examples#424]
Hi team,
I have created standalone minio instance in minikube cluster. But unable to browse the minio console in any browsers get error unable to connect to the server(i.e mino Pod instance).

NAME                                   READY   STATUS    RESTARTS       AGE
pod/minio-deployment-877b8596f-2k89m   1/1     Running   0              11s

service/minio-service   LoadBalancer   ip   ip       9000:30656/TCP                  11s

devivara@devivara-VirtualBox:~/Training/RAID$ kubectl logs pod/minio-deployment-877b8596f-2k89m
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
API: http://172.17.0.4:9000  http://127.0.0.1:9000

Console: http://172.17.0.4:41889 http://127.0.0.1:41889

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (41889), please use --console-address ":PORT" to choose a static port.

Pod is showing console ip but still unable to browse the console from any browser.

**Comment by LilMonk** [comment]
I have rectified the yaml for the standalone deployment now it works for me.
Can I  raise a pull request for the same?
