### ISSUE TITLE
Docker image has not been updated to reflect host name change (redis-slave ->  redis-replica)

### ISSUE THREAD

**Issue by warrensbox** [kubernetes/examples#437]
In main.go, on line 70, `redis-slave:6379` was refactored to `redis-replica:6379` on **Aug 12, 2021**.
See: https://github.com/kubernetes/examples/commit/69f7ab04f877ebf9988d33a8b13426a74d9348b3#diff-4db2d0a3cc62848825f64d1ac729ca2fd43579736f02c55b8a5bdac93220ebfe

However, the docker image hasn't been updated to reflect this change. The last time the image was updated was 4 years ago, on **Dec 22, 2017**. (See guestbook-controller.json - line 25)
https://github.com/kubernetes/examples/commit/40f5426f1ed1ada18b3e35407017f687c0e3dd64#diff-7e942bc4b4d9b4efdd1861b88c63b3692a8b24ec491c38256843632aa2e93f09

As a result, the application still looks for the old host name which is `redis-slave`. 
```
PANIC: dial tcp: lookup redis-slave on 10.100.0.10:53: no such host
goroutine 54 [running]:
```

Suggested fix: docker build the updated go file and update the tag to v4.

Others here who are facing this issue, please feel free to use my docker image  `warrensbox/guestbook:v4` until this is fixed.

Temporary fix ( guestbook-controller.json - line 25)
Change to [line 25](https://github.com/kubernetes/examples/blob/master/guestbook-go/guestbook-controller.json#L25) TO `"image":"warrensbox/guestbook:v4"`

**Comment by patrocinio** [comment]
This problem seems to have been fixed, as I see the code at https://github.com/kubernetes/examples/blob/master/guestbook-go/main.go#L79 as redis-replica
