### ISSUE TITLE
File staging/volumes/nfs/nfs-server-rc.yaml doesn't exist

### ISSUE THREAD

**Issue by huntersman** [kubernetes/examples#453]
I'm learning how to use NFS in K8s, so I read staging/volumes/nfs/README.md
In README.md, it mentions
```bash
$ kubectl create -f examples/staging/volumes/nfs/nfs-server-rc.yaml
```
But I can't find nfs-server-rc.yaml, could someone helps me, thank you!

**Comment by victtsl** [comment]
According to https://github.com/kubernetes/examples/pull/442:

1. staging/volumes/nfs/nfs-busybox-rc.yaml rename to staging/volumes/nfs/nfs-busybox-deployment.yaml
2. staging/volumes/nfs/nfs-server-rc.yaml rename to staging/volumes/nfs/nfs-server-deployment.yaml
3. staging/volumes/nfs/nfs-web-rc.yaml rename to staging/volumes/nfs/nfs-web-deployment.yaml
