### ISSUE TITLE
Image Tag Mismatch between k8s.gcr.io/guestbook:v3 and registry.k8s.io/guestbook:v3

### ISSUE THREAD

**Issue by highb** [kubernetes/examples#475]
When the image tag was switched over to the new `registry.k8s.io` container registry, it appears that the actual tags didn't get copied over quite right. When I deploy the `registry.k8s.io/guestbook:v3` image to my cluster, the front-end fails because it attempts to look up `redis-slave` and gets `no such host` when the manifests are configured to set up the service as `redis-replica`. This leads me to believe that a new version of the go guestbook needs to be pushed and then the tags in the manifests need to be updated.

Related commit:
https://github.com/kubernetes/examples/commit/538d302b41d0a865be8b8d80b843d0d9287dbbf3

**Comment by able8** [comment]
I checked the 2 images digest are identical. 
```
➜  ~ docker pull k8s.gcr.io/guestbook:v3
v3: Pulling from guestbook
...
Digest: sha256:8f333d5b72677d216b4eb046d655aef7be9f1380e06ca1c63dfa9564034e7e26
Status: Downloaded newer image for k8s.gcr.io/guestbook:v3
k8s.gcr.io/guestbook:v3
➜  ~ registry.k8s.io/guestbook:v3
zsh: no such file or directory: registry.k8s.io/guestbook:v3
➜  ~ docker pull registry.k8s.io/guestbook:v3
v3: Pulling from guestbook
...
Digest: sha256:8f333d5b72677d216b4eb046d655aef7be9f1380e06ca1c63dfa9564034e7e26
Status: Downloaded newer image for registry.k8s.io/guestbook:v3
registry.k8s.io/guestbook:v3
```

**Comment by T-Lakshmi** [comment]
I also verified and there is no issue present in this, both the image digests are same in below.
![2023-07-17 08-22-42](https://github.com/kubernetes/examples/assets/56723673/917d5772-754d-453f-998d-2914f7828e71)

**Comment by T-Lakshmi** [comment]
Closing the issue as there is no update from @highb.
Please feel free to reopen with necessary inputs if you are still facing this issue.
