### ISSUE TITLE
Cassandra Statefulset: How to expose the cluster?

### ISSUE THREAD

**Issue by ashwinipatankar** [kubernetes/examples#48]
I am trying out the cassandra -statefulset example. And can see all the three pods joined the cluster:
```
kubectl exec cassandra-0 -- nodetool status
Datacenter: DC1-K8Demo
======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.44.0.4  65.63 KiB  32           59.3%             91152a3e-c802-45bf-a4a9-33187a97b4c4  Rack1-K8Demo
UN  10.45.0.1  65.63 KiB  32           68.9%             ca7d39f4-341a-43d6-a180-23f89b124334  Rack1-K8Demo
UN  10.44.0.3  65.59 KiB  32           71.9%             b9075133-61ed-4fde-97c7-c2fd8d2b4234  Rack1-K8Demo
```

The out put of kubectl get service is:

```
kubectl get services
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
cassandra    None         <none>        9042/TCP   10s
kubernetes   10.96.0.1    <none>        443/TCP    50m

```
Now, I want to expose it and use from out side the cluster. 

Any help will be highly appreciated.

**Comment by ahmetb** [comment]
@ashwinipatankar consider taking a look at type:NodePort and type:LoadBalancer documentation here: 

- https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
- https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer

You can see how to expose a service externally at `frontend-service.yaml` on the guestbook example: https://github.com/kubernetes/examples/tree/master/guestbook

However it's not recommended to expose applications such as database to the outside world from a security perspective as anyone who can discover your IP address can try to break in or DDoS your database. If you have further questions, consider asking them on kubernetes-users@googlegroups.com mailing list.
