### ISSUE TITLE
guestbook-go not working as is

### ISSUE THREAD

**Issue by AntoineToussaint** [kubernetes/examples#506]
There are two issues:

- Docker build fails:

```shell
 => ERROR [stage-0 2/5] RUN go get github.com/codegangsta/negroni            github.com/gorilla/mux            github.com/xyproto/simpleredis                                              4.5s
------
 > [stage-0 2/5] RUN go get github.com/codegangsta/negroni            github.com/gorilla/mux            github.com/xyproto/simpleredis:
4.463 package github.com/xyproto/simpleredis: no Go files in /go/src/github.com/xyproto/simpleredis
```

Fix: add `/v2` to `simpleredis` version.

- Docker image referenced in Replica Controller aims replica redis client at deprecated service name `redis-slave`:

```shell
curl localhost:3000/rpush/k/v
PANIC: dial tcp: lookup redis-slave on 10.96.0.10:53: no such host
goroutine 5 [running]:
```

Fix: Deploy v4 version of `registry.k8s.io/guestbook` based on current `main.go` and update Kubernetes manifest.

I would do a PR but I am not sure what the process is to update the Docker image.

**Comment by dkwgit** [comment]
Also, the Makefile should be fixed. `make build` builds the image with `staging-k8s.gcr.io` but the manifest file for guestbook controller points to registry.k8s.io.

**Comment by lopter** [comment]
I also just ran into that issue, it was confusing.

**Comment by Martande8055** [comment]
I also faced the same issue.
I like to work on this issue, Please assign it to me.

**Comment by Martande8055** [comment]
hey, @pranav-pandey0804, can I work on this?

**Comment by pranav-pandey0804** [comment]
@Martande8055 sure, you don't need to ask to work on a issue

**Comment by pranav-pandey0804** [comment]
Just comment '/assign' and it will be assigned to you automatically

**Comment by pranav-pandey0804** [comment]
@Martande8055 also you need to sign the CLA if you haven't already and make sure to follow community guidelines

**Comment by pranav-pandey0804** [comment]
You can refer to this - https://github.com/kubernetes/kubernetes/community

**Comment by Martande8055** [comment]
Thank you so much @pranav-pandey0804 for guidance me.
