### ISSUE TITLE
guestbook: consider using single-instance redis deployment

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/examples#51]
Currently guestbook deployment consists of:

- frontend, 3 replicas (+service)
- redis-master, 1 replica (+service)
- redis-slave, 2 replicas (+service)

Redis reads go to slaves, writes go to master. However it seems like an overkill to me to have slave/master in this tutorial:

- it makes the tutorial ~30% longer and we have to explain why we have slave/master setup
- we have to maintain a custom redis image with entrypoint pointing to a custom script
- same story can be told with a single-instance redis image from Docker Hub.

cc: @jeffmendoza do you have any context you can provide?

**Comment by jeffmendoza** [comment]
This was the very first example. It certainly could be updated to be more basic and not use custom images.

**Comment by ahmetb** [comment]
Got it, I was curious if there was a specific lesson it teaches. Maybe redis-master service having ClusterIP that's being queried by redis-slave was one of the learnings. Or the GET_HOSTS_FROM=env part of the script probably teaches people about the env-var based service discovery. But kube-dns is broadly deployed at this point and exists in Minikube, I'm not worried about losing these learnings.
