### ISSUE TITLE
Broken image reference in guestbook example

### ISSUE THREAD

**Issue by mocdaniel** [kubernetes/examples#519]
The image reference `gcr.io/google-samples/gb-frontend:v4` in [`guestbook/frontend-deployment.yaml`](https://github.com/kubernetes/examples/blob/master/guestbook/frontend-deployment.yaml) is invalid, the tag doesn't seem to exist (anymore). 

After checking on gcr, it looks like there are no tags at all for `gb-frontend`, but only for the architecture-specific images, e.g. `gb-frontend-amd64` or `gb-frontend-arm`.

**Comment by neolit123** [comment]
i think this repository might contains some out-of-date examples, but they are not owned by SIG Cluster Lifecycle
/remove-sig cluster-lifecycle

**Comment by oussaka** [comment]
replace
```
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend
```
by

```
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
```
