### ISSUE TITLE
https will be supported in the k8s example

### ISSUE THREAD

**Issue by JuneZhao** [kubernetes/examples#58]
How to configure a SSL for the wordpress website in the docker image

**Comment by ahmetb** [comment]
Hi @JuneZhao. We currently do not have samples for this.

If you have a SSL certificate from a Certificate Authority, consider using an Ingress with TLS certificates. See this https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

If not, you might want to get a free certificate from Let's Encrypt using kube-lego https://github.com/jetstack/kube-lego. They have a tutorial on their repository you can follow.
