### ISSUE TITLE
Update Cassandra Example

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/examples#7]
I have a PR in the core repo that I need to move over to here.  Also how are we doing owners here?

**Comment by kargakis** [comment]
Can you also update the example to use a Deployment or ReplicaSet instead of a RC?

**Comment by ahmetb** [comment]
we haven't discussed any updates to OWNERS yet, we directly transferred the existing file over.

**Comment by chrislovecnm** [comment]
@kargakis I am planning on removing the RC example, as I can no longer recommend using that since we have stateful sets.

**Comment by chrislovecnm** [comment]
@ahmetb you can assign this to me if you like. I have been maintaining the C* example.

**Comment by ahmetb** [comment]
@chrislovecnm any updates?

**Comment by chrislovecnm** [comment]
Hopefully this week

**Comment by ahmetb** [comment]
@chrislovecnm #38 just made a bunch of updates to the Cassandra tutorial, feel free to send PRs if you think it can be improved.
