### ISSUE TITLE
Not able to run spark-submit iteractively on zeppelin container.

### ISSUE THREAD

**Issue by luciferksh** [kubernetes/examples#90]
I have setup spark cluster in our k8s infrastructure. And i was trying to submit spark program through spark-submit in zepelin container as follow -
```shell
kubectl exec zeppelin-controller-nqz79 -it spark-submit --class com.ibm.cedp.spark.JavaSparkPi /home/sidartha/bazel/bazel-bin/java/com/ibm/cedp/spark/SparkPi_deploy.jar

```
And getting follwing error -
```shell
Error: unknown flag: --class

```

**Comment by luciferksh** [comment]
Hi @sebgoa , Could you please helpme on this. Thanks!

**Comment by congfairy** [comment]
Hi, so how did you solve this problem?thanks!
