### ISSUE TITLE
OMS dameonset takes a long time to get heartbeat success

### ISSUE THREAD

**Issue by Gcastelo** [kubernetes/examples#92]
Hi,

I've deployed the OMS Agent dameonset to a k8 cluster and configured with the correct OMS Id and key, after following this [OMS Agent setup](https://github.com/kubernetes/examples/tree/master/staging/oms)

`omsagent-f35cw                          1/1       Running   0          15m       10.244.0.189   k8s-agentpool1-41733846-0`
`omsagent-v9dr1                          1/1       Running   0          18m       10.244.1.10    k8s-master-41733846-0`

After deploying the pod running in the k8 agentpool1 takes around 1h to get a successful heartbeat:

`2017-09-07 10:44:34 +0000 [error]: Unable to resolve the IP of ‘omsagent-f35cw’: getaddrinfo: Servname not supported for ai_socktype`
`2017-09-07 10:44:34 +0000 [warn]: Failed to get the IP for omsagent-f35cw.`
`2017-09-07 11:58:21 +0000 [info]: Heartbeat success`

Sometimes ssh'ing into the cluster and doing 
`docker restart k8s_omsagent_omsagent-w48t1_default_d3d99e53-9312-11e7-99dd-000d3a260024_0` 
solves the issue and the logs start to show on OMS.

Any help on what might be going on?

Thank you

**Comment by ahmetb** [comment]
cc: @OguzPastirmaci is the owner of the OMS example.

**Comment by OguzPastirmaci** [comment]
We have improved the solution, could you try again with the following instructions:
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers#configure-an-oms-agent-for-kubernetes

I will also update the example in this repo to reflect the changes.

**Comment by ahmetb** [comment]
@OguzPastirmaci if you have a separate repo to host this example on Microsoft properties (e.g. github org) that would be more preferable than having it here. We're trying to move 3rd party software/vendor examples out of this repository.

I see you are already using https://github.com/Microsoft/OMS-docker which is great. So I suggest sending a pull request to delete manifests and update the README.md saying "This example is deprecated, find the up to date example at -URL-".

**Comment by OguzPastirmaci** [comment]
Good idea, created #95.

**Comment by Gcastelo** [comment]
@OguzPastirmaci I'll have a look and come back as soon as possible.

Could you explain what could be causing the current issue?

Thank you

**Comment by OguzPastirmaci** [comment]
I don't know what could be causing the issue you're having but I reached out to the PM of the feature about it. I'll update the issue as soon as I hear from them.

**Comment by OguzPastirmaci** [comment]
The cause of your issue might be the labels below in the new version that are used to set the agent and Docker provider versions.

agentVersion: 1.4.0-12
dockerProviderVersion: 10.0.0-25

**Comment by beardman** [comment]
@OguzPastirmaci, I tried the suggested solution, of setting both agentVersion and dockerProviderVersion, but noticed no improvements or changes.

The behaviour is still the same as @Gcastelo mentioned above. First successful heartbeat only shows up in the agent logs over 1 hour after it was launched.

Any other ideas/suggestions of what might be the cause of this issue?

**Comment by OguzPastirmaci** [comment]
@keikhara, any ideas why it would take over an hour for the logs to show up?
