### ISSUE TITLE
[Feature request] Add Ethereum private chain example

### ISSUE THREAD

**Issue by kairen** [kubernetes/examples#93]
Could I add a blockchain example to run the Ethereum private chain cluster on Kubernetes? It will be like this repos [Kubereum](https://github.com/kairen/kubereum).

**Comment by ahmetb** [comment]
We are currently not accepting new examples into this repository and trying to move existing ones into separate repos. Furthermore, your example is another 3rd party software integration that  does not constitute a Kubernetes Example that demonstrates core features and has an accompanying tutorial.

 I recommend you to create your own repository (which it looks like there's already one) and gather a community around it. If it becomes popular, consider making it an officially maintained Helm chart, and if it gets really popular, consider applying for a transfer to `kubernetes-incubator` organization. But most likely you won't need it as your repo already looks fine.

**Comment by kairen** [comment]
@ahmetb Okay, thanks you for your reply!
